<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Dog</name>
   <tag></tag>
   <elementGuidId>80288b2b-3e8a-46ae-a337-02d88875fe58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.option-card-title.option-card-title-small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div[3]/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0bbb6854-7480-44af-a4f5-c44ddbc48d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-card-title option-card-title-small</value>
      <webElementGuid>001ec5b8-07c2-4748-8e40-3253c43b4f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dog</value>
      <webElementGuid>beba6c08-a7f4-42a8-af14-b80776507375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container survey survey-combo&quot;]/div[@class=&quot;container main-content&quot;]/div[@class=&quot;part-content part-content-block&quot;]/div[@class=&quot;options-container options-container-images form-section form-section-multiple form-section-multiple-image&quot;]/div[@class=&quot;option-card&quot;]/div[@class=&quot;option-card-content&quot;]/h3[@class=&quot;option-card-title option-card-title-small&quot;]</value>
      <webElementGuid>834e58e2-8f6c-4c19-be0b-e7d77a3747b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[3]/div/div/h3</value>
      <webElementGuid>20220883-7982-4027-9412-cc3e7dbf2af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What type of pet do you have?'])[1]/following::h3[1]</value>
      <webElementGuid>22d3ca4e-c59c-4356-89e9-128cd7abba2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age (Must be over 18)'])[1]/following::h3[1]</value>
      <webElementGuid>f0733c01-c7c4-4e56-aa4b-1e6b8e5f94de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose an option'])[1]/preceding::h3[2]</value>
      <webElementGuid>a75f37b0-9623-411a-a62a-3c083ffd5af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dog']/parent::*</value>
      <webElementGuid>9b6cb31d-ba61-4802-becf-1d93b2a67ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>68bbbcc1-b734-4159-a0a5-303e685953db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Dog' or . = 'Dog')]</value>
      <webElementGuid>3dc6b134-f740-4bf0-ab2b-4ba175b5c9d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
