<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Age (Must be over 18)_age</name>
   <tag></tag>
   <elementGuidId>7430e23e-d591-404d-bdea-8a8fcc7ec0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#age</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='age']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9a05e26-f5bd-46bf-be02-193ee7e81f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>84a92b57-e534-4588-ad34-383d1226d90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>age</value>
      <webElementGuid>8e480f4f-d274-4374-925f-fda18a8a5138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>age</value>
      <webElementGuid>236dfe4e-94d2-421f-948b-60969e65f419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>b7bb574e-92d1-410f-878e-9621cf4a1cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;age&quot;)</value>
      <webElementGuid>4e32883b-b961-47b3-b72b-e40110de3144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='age']</value>
      <webElementGuid>69bac936-744d-4579-90f1-3c5b30f8430b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>45b78aa0-3a8e-4a34-9ca5-da49d8fb6d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>eff2dbe9-1e34-4f71-a6f9-cc81be2c22d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'age' and @id = 'age' and @placeholder = '18']</value>
      <webElementGuid>29ebd150-1aea-4994-ab9e-9c5c8a1caf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
