<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Landlords waive pet fees or deposits for ESAs</name>
   <tag></tag>
   <elementGuidId>602f74c0-bde5-4f9d-95bf-4501e8e4fd7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/ol/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8a213e21-63e2-4c69-8d16-bbe8b8c2d629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Landlords waive pet fees or deposits for ESAs</value>
      <webElementGuid>a73b83f5-b1e7-4e87-b829-03aa8b177f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container survey survey-combo&quot;]/div[@class=&quot;container main-content&quot;]/div[@class=&quot;part-content&quot;]/ol[@class=&quot;bullets&quot;]/li[1]</value>
      <webElementGuid>c8b1cd7b-cba2-4527-8ba1-8ce552d8b4b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/ol/li</value>
      <webElementGuid>fa6a90d6-e010-43bb-850a-2b8d879fa92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Landlords']/parent::*</value>
      <webElementGuid>c2ac3369-903f-42f0-b990-9e6816243614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>07ace1d2-6c62-432b-86e8-d7b6c7344d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Landlords waive pet fees or deposits for ESAs' or . = 'Landlords waive pet fees or deposits for ESAs')]</value>
      <webElementGuid>2b6ce1db-ae45-4e7b-a817-e302bb52fcff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
