<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card Information___privateStripeFrame2774</name>
   <tag></tag>
   <elementGuidId>c7cdd01a-5a08-4343-9d3a-39278e3c295b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame2774&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame2774']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7dac5d03-c0a8-4b9b-921a-78d8923c30e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame2774</value>
      <webElementGuid>d726b0ee-c75f-412d-b361-cc8bcfccaf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8ed32a7-6850-4bb2-8174-157117698fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df5ad598-dafe-4425-8e90-71d102916d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3aaa453c-4276-4149-bc97-a783bab5cf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e3b25cd9-c4ba-49f8-a71d-951a6210e3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-de6711d31c768a258fb19e0a5db19194.html#__shared_params__[version]=v3&amp;wait=true&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][fontSize]=16px&amp;style[base][fontFamily]=%22Raleway%22%2C+sans-serif&amp;style[base][color]=%23292D3E&amp;style[base][::placeholder][color]=%236c757d&amp;style[base][padding]=0.375rem+2.25rem+0.375rem+0.75rem&amp;style[base][lineHeight]=1.7&amp;style[invalid][border]=1px+solid+%23F04D30&amp;style[invalid][color]=%23F04D30&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_N4Qli5H2BgLQkJRebGL34sq0&amp;frameMessagingStrategy=postMessage&amp;referrer=https%3A%2F%2Ftest-checkout.certapet.com%2F%3Fproduct%3D1&amp;controllerId=__privateStripeController2771</value>
      <webElementGuid>a321490c-865e-4412-8593-894aacd05cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure card number input frame</value>
      <webElementGuid>636ef02e-d769-47b4-ad72-3d8a40f39053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 column-right&quot;]/section[@class=&quot;form-container&quot;]/form[1]/div[@class=&quot;form-line mt-0&quot;]/div[@class=&quot;form-control mt-0 rounded-bottom-0 StripeElement--empty form-control-focus&quot;]/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>f91d7231-fa84-4b9c-9370-82f6f377c1ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame2774']</value>
      <webElementGuid>1c34276e-e2fb-4144-8118-2a109f276a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/section/form/div[3]/div/div/iframe</value>
      <webElementGuid>2b174a1e-f47d-44bd-bde6-b15aa1b886a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/iframe</value>
      <webElementGuid>3a351dfd-eba8-4b06-9281-dd99fc693594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame2774' and @src = 'https://js.stripe.com/v3/elements-inner-card-de6711d31c768a258fb19e0a5db19194.html#__shared_params__[version]=v3&amp;wait=true&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][fontSize]=16px&amp;style[base][fontFamily]=%22Raleway%22%2C+sans-serif&amp;style[base][color]=%23292D3E&amp;style[base][::placeholder][color]=%236c757d&amp;style[base][padding]=0.375rem+2.25rem+0.375rem+0.75rem&amp;style[base][lineHeight]=1.7&amp;style[invalid][border]=1px+solid+%23F04D30&amp;style[invalid][color]=%23F04D30&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_N4Qli5H2BgLQkJRebGL34sq0&amp;frameMessagingStrategy=postMessage&amp;referrer=https%3A%2F%2Ftest-checkout.certapet.com%2F%3Fproduct%3D1&amp;controllerId=__privateStripeController2771' and @title = 'Secure card number input frame']</value>
      <webElementGuid>4df45e2a-718c-4f99-8be0-e07a6d0ce1e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
