<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card Information___privateStripeFrame2776</name>
   <tag></tag>
   <elementGuidId>e3acada1-e805-4a42-9ef4-b16bf91e64be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame2776&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame2776']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5ec98865-40f5-44f7-bc64-857d6492ec3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame2776</value>
      <webElementGuid>e1c15bcc-b3cd-4557-ad54-a37e49fc4af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33f189fa-afda-48ce-86d6-702fc79e8f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8aa63553-c06e-4dcc-90e6-77a83b12f2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c07e6759-0278-46de-9268-19e747a74bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1fdc4a7c-e070-47a5-83af-2f4da44c6a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-de6711d31c768a258fb19e0a5db19194.html#__shared_params__[version]=v3&amp;wait=true&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][fontSize]=16px&amp;style[base][fontFamily]=%22Raleway%22%2C+sans-serif&amp;style[base][color]=%23292D3E&amp;style[base][::placeholder][color]=%236c757d&amp;style[base][padding]=0.375rem+2.25rem+0.375rem+0.75rem&amp;style[base][lineHeight]=1.7&amp;style[invalid][border]=1px+solid+%23F04D30&amp;style[invalid][color]=%23F04D30&amp;rtl=false&amp;componentName=cardExpiry&amp;keyMode=test&amp;apiKey=pk_test_N4Qli5H2BgLQkJRebGL34sq0&amp;frameMessagingStrategy=postMessage&amp;referrer=https%3A%2F%2Ftest-checkout.certapet.com%2F%3Fproduct%3D1&amp;controllerId=__privateStripeController2771</value>
      <webElementGuid>f2519d45-3d69-4483-b070-4015cbe71c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure expiration date input frame</value>
      <webElementGuid>5d80284b-83ee-4b1e-9995-9a80f252ef8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 column-right&quot;]/section[@class=&quot;form-container&quot;]/form[1]/div[@class=&quot;form-line d-flex mt-0 row-cols-2 flex-wrap&quot;]/div[@class=&quot;col-6 ps-0&quot;]/div[@class=&quot;form-control mt-0 rounded-top-0 border-start-0 border-top-0 rounded-bottom-end-0 StripeElement--empty form-control-focus&quot;]/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>00ec5164-2e24-44fa-99c9-fe7b4d656e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame2776']</value>
      <webElementGuid>ea397f35-e323-44ee-8623-d45e86b5a718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/section/form/div[4]/div[2]/div/div/iframe</value>
      <webElementGuid>cfdc5547-231d-4d2c-ac00-0b74f18107ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/iframe</value>
      <webElementGuid>5b07f729-b53a-421c-b29a-deee85762121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame2776' and @src = 'https://js.stripe.com/v3/elements-inner-card-de6711d31c768a258fb19e0a5db19194.html#__shared_params__[version]=v3&amp;wait=true&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][fontSize]=16px&amp;style[base][fontFamily]=%22Raleway%22%2C+sans-serif&amp;style[base][color]=%23292D3E&amp;style[base][::placeholder][color]=%236c757d&amp;style[base][padding]=0.375rem+2.25rem+0.375rem+0.75rem&amp;style[base][lineHeight]=1.7&amp;style[invalid][border]=1px+solid+%23F04D30&amp;style[invalid][color]=%23F04D30&amp;rtl=false&amp;componentName=cardExpiry&amp;keyMode=test&amp;apiKey=pk_test_N4Qli5H2BgLQkJRebGL34sq0&amp;frameMessagingStrategy=postMessage&amp;referrer=https%3A%2F%2Ftest-checkout.certapet.com%2F%3Fproduct%3D1&amp;controllerId=__privateStripeController2771' and @title = 'Secure expiration date input frame']</value>
      <webElementGuid>6c67a90d-a7e1-4e80-b771-53e149f2e758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
