<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card Information___privateStripeFrame2775</name>
   <tag></tag>
   <elementGuidId>88aebd1c-e609-4ced-8041-a25543c592f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame2775&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame2775']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>48e2f7d5-6ff7-459d-b37d-86ef03af1184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame2775</value>
      <webElementGuid>3cbe2d3b-69df-4bc5-ae1b-cfed3b19b4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>58083ed9-d36b-4876-a5a1-2d8a9cba0fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec5fc312-2f65-4113-89b7-5e6e98048d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7d3f2188-10cd-436a-bfbe-bce7200c7249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>15d213d4-6b45-47ac-830b-0c6f069d7a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-de6711d31c768a258fb19e0a5db19194.html#__shared_params__[version]=v3&amp;wait=true&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][fontSize]=16px&amp;style[base][fontFamily]=%22Raleway%22%2C+sans-serif&amp;style[base][color]=%23292D3E&amp;style[base][::placeholder][color]=%236c757d&amp;style[base][padding]=0.375rem+2.25rem+0.375rem+0.75rem&amp;style[base][lineHeight]=1.7&amp;style[invalid][border]=1px+solid+%23F04D30&amp;style[invalid][color]=%23F04D30&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_N4Qli5H2BgLQkJRebGL34sq0&amp;frameMessagingStrategy=postMessage&amp;referrer=https%3A%2F%2Ftest-checkout.certapet.com%2F%3Fproduct%3D1&amp;controllerId=__privateStripeController2771</value>
      <webElementGuid>405af563-4db6-4387-84bd-87ff5a4f972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure CVC input frame</value>
      <webElementGuid>230d3faa-9886-4380-8363-e96d14dba6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 column-right&quot;]/section[@class=&quot;form-container&quot;]/form[1]/div[@class=&quot;form-line d-flex mt-0 row-cols-2 flex-wrap&quot;]/div[@class=&quot;col-6 rounded-end-0 pe-0&quot;]/div[@class=&quot;form-control mt-0 rounded-top-0 border-top-0 rounded-right-0 StripeElement--empty&quot;]/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>5b7baac2-dd36-43f2-ba01-16e66f364f00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame2775']</value>
      <webElementGuid>b857833e-eea6-427a-be53-1085f234558c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/section/form/div[4]/div/div/div/iframe</value>
      <webElementGuid>2dc31bfd-d88e-4d54-a1f6-c318f48e1068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/iframe</value>
      <webElementGuid>cda7c3b9-59ea-4443-94b5-3526e2cf1057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame2775' and @src = 'https://js.stripe.com/v3/elements-inner-card-de6711d31c768a258fb19e0a5db19194.html#__shared_params__[version]=v3&amp;wait=true&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][fontSize]=16px&amp;style[base][fontFamily]=%22Raleway%22%2C+sans-serif&amp;style[base][color]=%23292D3E&amp;style[base][::placeholder][color]=%236c757d&amp;style[base][padding]=0.375rem+2.25rem+0.375rem+0.75rem&amp;style[base][lineHeight]=1.7&amp;style[invalid][border]=1px+solid+%23F04D30&amp;style[invalid][color]=%23F04D30&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_N4Qli5H2BgLQkJRebGL34sq0&amp;frameMessagingStrategy=postMessage&amp;referrer=https%3A%2F%2Ftest-checkout.certapet.com%2F%3Fproduct%3D1&amp;controllerId=__privateStripeController2771' and @title = 'Secure CVC input frame']</value>
      <webElementGuid>d4ade630-e485-4e17-83a7-b6ce06c52189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
