<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name of Cardholder_holder</name>
   <tag></tag>
   <elementGuidId>17d83f93-f789-4f68-b74a-dbe0c6b2c422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#holder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='holder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3251b89-5fd3-4924-a6b8-141735b7ea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c5940f8-fc31-4b91-8c70-b8ff41fb6388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>holder</value>
      <webElementGuid>ac4d76ac-2b34-4ed2-9efd-2df61f51dd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>holder-help</value>
      <webElementGuid>e15aa35c-bc61-4cb9-a450-757678859ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Doe</value>
      <webElementGuid>8be1e1a8-c07d-413d-8858-f772e3b9c046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>ac62c18b-87c2-4be2-a9b9-611f6c9ccef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;holder&quot;)</value>
      <webElementGuid>946875b5-3bb3-4089-9804-1fd83f0e30be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='holder']</value>
      <webElementGuid>ccd6e96c-8602-4943-b01c-dc68fcf3e1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/section/form/div[5]/input</value>
      <webElementGuid>7295810f-e68e-4e5c-a4ad-9fdd87ebe8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/input</value>
      <webElementGuid>9ca18896-36df-4a64-a91e-f8601c4647d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'holder' and @placeholder = 'John Doe']</value>
      <webElementGuid>faedc20e-4274-43ea-add6-4bd7394f21b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
