<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Often</name>
   <tag></tag>
   <elementGuidId>0924043e-3b2f-4416-b49e-88a2c1b884a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b66d8dab-a0cc-4dd7-b5ba-d83d593f8490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-card option-card-label  </value>
      <webElementGuid>bb438812-9c13-460a-abe5-415d9c058360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Often</value>
      <webElementGuid>0357c1fc-d65f-4e03-8f6e-9c9c6bbc548d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-container survey survey-travel&quot;]/div[@class=&quot;container main-content&quot;]/div[@class=&quot;part-content part-content-block&quot;]/div[@class=&quot;options-container options-container-labels form-section form-section-multiple form-section-multiple-label&quot;]/div[@class=&quot;option-card option-card-label&quot;]</value>
      <webElementGuid>926d5517-fcb7-4617-8fb9-8eb31252e151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[4]</value>
      <webElementGuid>a41d09b3-10c8-4efb-ad54-8f3f3203fc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sometimes'])[1]/following::div[1]</value>
      <webElementGuid>5e903875-ff70-46ef-81b5-5bd71d1405d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rarely'])[1]/following::div[3]</value>
      <webElementGuid>f70c59d2-0ce5-4b9b-b5d9-fd1195303f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Always'])[1]/preceding::div[2]</value>
      <webElementGuid>2e2c5f5a-6e3d-449b-bc52-8959ab193a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>3f028267-4812-4af2-838c-664e55dc3c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Often' or . = 'Often')]</value>
      <webElementGuid>51f6e950-f402-476e-b1ad-a8ed67d250f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
