<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_spinner</name>
   <tag></tag>
   <elementGuidId>41888a2a-5dd3-45e8-8ab7-7f691f49adc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.spinner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75fdf7bc-3e39-4415-8066-8bd7db5dbfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spinner</value>
      <webElementGuid>7e7987b4-c449-4064-9ad3-d06b1b5eddfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;loader-overlay&quot;]/div[@class=&quot;loader-container&quot;]/div[@class=&quot;spinner&quot;]</value>
      <webElementGuid>95306a87-200e-445e-8f94-7b441bdf1773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>65c98952-ab1d-4200-97a6-07c7b33f5cc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
